name: Build Spadekit

on:
  push:
    branches:
      - main
      - release
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow Dispatch Event
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SPADEKIT_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/crugroup/spadekit/actions/workflows/docker-image.yml/dispatches \
          -d '{"ref":"${{ github.ref }}","inputs":{"branch":"${{ github.ref }}"} }'
